# Generated by Django 2.0.4 on 2018-04-29 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20180429_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subcategory_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.Category'),
        ),
    ]
